/**
 * This file was generated by Payload.
 * It contains the import map for server-side component resolution.
 * DO NOT MODIFY IT BY HAND.
 */

import type { ImportMap } from 'payload'

export const importMap: ImportMap = {
  '@payloadcms/richtext-slate/client#RichTextCell': {
    path: '@payloadcms/richtext-slate/client#RichTextCell',
    exportName: 'RichTextCell',
  },
  '@payloadcms/richtext-slate/client#RichTextField': {
    path: '@payloadcms/richtext-slate/client#RichTextField',
    exportName: 'RichTextField',
  },
}

